# Generated by Django 3.1.2 on 2021-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt1', models.CharField(max_length=100)),
                ('opt2', models.CharField(max_length=100)),
                ('opt3', models.CharField(max_length=100)),
                ('opt1_count', models.IntegerField(default=0)),
                ('opt2_count', models.IntegerField(default=0)),
                ('opt3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
